#ifndef DEBUG_MACRO_HPP
#define DEBUG_MACRO_HPP

// #define TRANSFORM_VIEWPOINT_TIMER

// #define PROCESSING_TIMER

// #define PACKING_TIMER

// #define SENDER_TIMER

#define FINAL_NUMBER_DEBUG

// #define SETUP_LINE_TIMER

#define FPS_MEASURE
// #define RUNNINT_TIME 30.0

#endif // DEBUG_MACRO_HPP